resource "aws_key_pair" "followme_key" {
  key_name   = "followme-key"
  public_key = file("${path.module}/key/followme-key.pub")

  tags = {
    description = "Key pair generated by Terraform"
  }
}
